version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leadsdb
    volumes:
      - ./init-db.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - local

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_BASE_URL=${API_BASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - local

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=${API_BASE_URL}
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - local

networks:
  local:
    driver: bridge
